services:
    Elias.welcomerobot.listener:
        class: Elias\autopost\event\listener
        arguments:
            - @config
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }